### ISSUE TITLE
failed deploy to portainer returns exit(0)

### ISSUE THREAD

**Issue by sig-dan** [robkaandorp/drone-portainer#4]
```
(node:1) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'docker-compose.staging.yml'
--
102 | at Object.openSync (fs.js:443:3)
103 | at Object.readFileSync (fs.js:343:35)
104 | at /app/dist/index.js:117:42
105 | at Generator.next (&lt;anonymous&gt;)
106 | at fulfilled (/app/dist/index.js:5:58)
107 | at process._tickCallback (internal/process/next_tick.js:68:7)
```

If you specify a non-existing compose_file in settings, the plugin can return a 0 exit code while failing.

compose_file: **docker-compose.staging.yml**
```

 - name: deploy to staging
    image: robkaandorp/drone-portainer
    settings:
      portainer_url: https://${PORTAINER_URI}
      portainer_username: ${PORTAINER_USER}
      portainer_password:
        from_secret: portainer_password
      compose_file: docker-compose.staging.yml

```
It will work correctly if the file exists.

suggest returning process.exit(1) on unhandled error
